modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/USER/REPO/issues"

[[mods]]
modId="bldooptimised"
version="1.0.0"
displayName="BldoOptimised"
displayURL="https://github.com/USER/REPO"
authors="Author"
description='''
BldoOptimised
'''

[[mixins]]
config="bldooptimised.mixins.json"